### ISSUE TITLE
Unnecessary Alert

### ISSUE THREAD

**Issue by Aktimoose** [cgytrus/IAmNotHacking#1]
The anticheat only clears progress if you have _both_ less than 10 attempts and 50 jumps, yet the mod triggers an alert if either one of the conditions is true.
![image](https://github.com/cgytrus/IAmNotHacking/assets/44620677/7df3dddf-4497-4e64-953a-8e0a11a58418)

I tested this by saving and loading my stats onto my phone, and an insane 8 star that I beat in less than 10 attempts but with more than 50 jumps loaded complete entirely fine.
![image](https://github.com/cgytrus/IAmNotHacking/assets/44620677/1e38b292-4cea-4f56-ba25-1a31e4bf5167)

**Comment by cgytrus** [comment]
fixed in v1.0.1
